title: JAELYN
remote_theme: pages-themes/midnight@v0.2.0
markdown: kramdown
image: https://f4.bcbits.com/img/a3601614262_10.jpg
plugins: 
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag

